### ISSUE TITLE
git hooks - where to find?

### ISSUE THREAD

**Issue by omzoqasd** [ssciwr/sustainable_development_course#2]
Hi Inga,

may you give a little bit more input where to find .git/hooks and how to use them?

cheers 
Johannes

**Comment by iulusoy** [comment]
They are in your checked out repository, for example if you checked out this repository already, then in the main directory there will be a .git folder and in it a hooks folder with some sample hooks.  
`sustainable_development_course/.git/hooks`          pre-push.sample     update.sample - but we will work on this mostly in the live lesson.
