### ISSUE TITLE
add feedback on file "NEXT_TIME.md" - unit1

### ISSUE THREAD

**Issue by omzoqasd** [ssciwr/sustainable_development_course#3]
Hi Inga,

some kind short suggestions for the text time: 
unit1
- add more context information and steps information
- provide after each unit a updated repo, which contains the last "best solution"

(I liked today that the next tasks in the live session in wonder.me where written in the chat additionally and not only spoken)

Cheers Johannes

**Comment by iulusoy** [comment]
Thank you for the suggestions! For the "best solution" repo, there is [this one](https://github.com/iulusoy/team0) that I shared with you via email: - after this week's unit is "complete" (by Tuesday), I will again update it to a possible solution to the tasks in unit 2. 

Or would you rather like something that contains the last steps from the live session?

**Comment by omzoqasd** [comment]
sometimes it would be useful to compare the steps from the session with the own repo for troubleshooting / figuring out what is still wrong and not working. So, the last steps from the live session.
