### ISSUE TITLE
error: pre-commit install not on PATH

### ISSUE THREAD

**Issue by omzoqasd** [ssciwr/sustainable_development_course#4]
Dear all,

used "pip3 install pre-commit" in WSL2 terminal. Has someone an idea on the following?
WARNING: The scripts pre-commit, pre-commit-validate-config and pre-commit-validate-manifest are installed in '/home/MYUSER/.local/bin' which is not on PATH.

thank you 
Johannes

**Comment by iulusoy** [comment]
You would need to add the path '/home/MYUSER/.local/bin' to you PATH variable, as does the [install script](https://github.com/ssciwr/sustainable_development_course/blob/main/preparation/install.sh) that you ran before the first session.

**Comment by iulusoy** [comment]
Please let me know if your path had been added your .bashrc file - if it has and the problem still persists, it may be that you are using a different shell than bash, for example.

**Comment by omzoqasd** [comment]
solved everything, thank you
