### ISSUE TITLE
Can't find requirements.txt

### ISSUE THREAD

**Issue by bellerophons-pegasus** [ssciwr/sustainable_development_course#6]
In the preparation for unit 3 a `requirements.txt` file is mentioned, which should be here somewhere, but I could not find it.

**Comment by bellerophons-pegasus** [comment]
Ah, maybe the link should be updated, because the requirements is in the team0-repo: https://github.com/iulusoy/team0

**Comment by iulusoy** [comment]
Thanks for pointing that out, it has been fixed!
