### ISSUE TITLE
Already push local sphinx documentation to GitHub?

### ISSUE THREAD

**Issue by bellerophons-pegasus** [ssciwr/sustainable_development_course#7]
While preparing for unit3 I would like to make sure, if we are already supposed to push the local sphinx documentation to the remote repository. 

* the build folder is excluded via `.gitignore`
* what about the files `make.bat` and `Makefile` in `doc`?
* should everything in `source` be included?

**Comment by iulusoy** [comment]
The build folder will be excluded from the repository, but all the other files should be there (see the [example repo](https://github.com/iulusoy/team0)).
