### ISSUE TITLE
Linking repositories not owned by iulusoy 

### ISSUE THREAD

**Issue by bellerophons-pegasus** [ssciwr/sustainable_development_course#9]
I just tried to link our repository to the [project page](https://github.com/users/iulusoy/projects/1) you suggested, but there it is not possible to add external repositories.

**Comment by iulusoy** [comment]
Can you try again? I gave you admin rights to the project, maybe that will help.

**Comment by bellerophons-pegasus** [comment]
Mh no, that does not work either. 

From the documentation
> Anyone with write permissions to a project board can link repositories owned by that organization or user account to the project board.

A workaround could be a none automated column `Related Repositories`. There with each note a link to a repository can be added.

**Comment by bellerophons-pegasus** [comment]
I've tried it out with our repository.

**Comment by iulusoy** [comment]
Unfortunately linking your repos does not work. All others, please consider adding your repositories to the project page as Team14 has done.
